[ui]
default-command = "log"

[user]
name = "Michael Hanson"
email = "186724+mybuddymichael@users.noreply.github.com"

[signing]
behavior = "own"
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJe7nonDPCIbdcv5hXNLmekIoIYjiP7fq1C9aZFKYuOU"
backends.ssh.program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"

[templates]
log = "builtin_log_oneline"

[template-aliases]
# Username part of the email address
'format_short_signature(signature)' = 'signature.name()'
'format_short_signature_oneline(signature)' = 'signature.name()'
'format_timestamp(timestamp)' = 'timestamp.local().ago()'
