[ui]
diff-formatter = ":git"
default-command = "ta"
pager = ["sh", "-c", "diff-so-fancy | less --tabs=2 -RFX"]
diff-editor = ":builtin"

[user]
name = "Michael Hanson"
email = "186724+mybuddymichael@users.noreply.github.com"

[signing]
behavior = "own"
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJe7nonDPCIbdcv5hXNLmekIoIYjiP7fq1C9aZFKYuOU"
backends.ssh.program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"

[aliases]
# From the current commit to the commit that is in trunk that we branched from.
t = ["log", "-r", "heads(::trunk() & ::@)::@"]
# Everything that is a descendent of the commit that we branched off of trunk.
ta = [
  "log",
  "-r",
  "heads(::trunk() & ::@):: ~ (heads(::trunk() & ::@)..untracked_remote_bookmarks() ~ ::tracked_remote_bookmarks())",
]
# Everything that is a descendent of the commit that we branched off of trunk, including remote bookmarks.
tar = ["log", "-r", "heads(::trunk() & ::@)::"]

[git]
sign-on-push = true

[templates]
log = 'builtin_log_oneline'

[template-aliases]
'format_short_id(id)' = 'id.shortest(3)'
'format_short_signature(signature)' = 'signature.name()'
'format_short_signature_oneline(signature)' = '''
if(signature.name() == "Michael Hanson",
  label("author me",  "👋 Me"),
  signature.name()
)
'''
'format_timestamp(timestamp)' = 'timestamp.local().ago()'
builtin_log_node = '''
coalesce(
  if(!self, label("elided", "~")),
  label(
    separate(" ",
      if(current_working_copy, "working_copy"),
      if(immutable, "immutable"),
      if(conflict, "conflict"),
    ),
    coalesce(
      if(current_working_copy, "→"),
      if(immutable, "◆"),
      if(conflict, "×"),
      "○",
    )
  )
)
'''

description_placeholder = 'label("description placeholder", "(no desc)")'

[colors]
prefix = { bold = true, underline = true }

author = 'bright black'
'author me' = { fg = 'magenta' }
'working_copy author me' = 'green'
'working_copy author' = 'green'

bookmark = 'red'
bookmarks = 'red'
git_head = 'blue'

change_id = 'white'
'working_copy change_id' = 'green'

timestamp = 'bright black'
'working_copy timestamp' = 'white'

'description placeholder' = 'yellow'

empty = "cyan"
'working_copy empty' = { fg = "cyan", bold = true }

'working_copy empty description placeholder' = 'yellow'

'node working_copy' = { fg = 'green', bold = true }

'diff removed token' = { underline = false }
'diff added token' = { underline = false }
'diff token' = { underline = false }

[lazyjj.keybinds.log_tab]
save = "Enter"
