[settings]
dotfiles.root = "."

[dotfiles]
"~/.config/mise/config.toml" = { source = "mise/config.toml", mode = "symlink" }
"~/.config/git" = { source = "git", mode = "symlink" }
"~/.config/jj" = { source = "jj", mode = "symlink" }
"~/.config/fish" = { source = "fish", mode = "symlink" }
"~/.config/ghostty" = { source = "ghostty", mode = "symlink" }
"~/.config/atuin/config.toml" = { source = "atuin/config.toml", mode = "symlink" }
"~/.config/btop" = { source = "btop", mode = "symlink-each" }
"~/.pi" = { source = "pi", mode = "symlink" }
"~/.hammerspoon" = { source = "hammerspoon", mode = "symlink" }
"~/.aerospace.toml" = { source = "aerospace/aerospace.toml", mode = "symlink" }
"~/.aerospace-debug.toml" = { source = "aerospace/aerospace-debug.toml", mode = "symlink" }
"~/.agents" = { source = "agents", mode = "symlink" }
