#!/usr/bin/env bash

export WHITE=0xffffffff
export BLACK=0xff000000
export RED=0xfffda7a6
export GREEN=0xffa6da95
export BLUE=0xff8aadf4
export YELLOW=0xffffe4bf
export ORANGE=0xfff5a97f
export MAGENTA=0xffc6a0f6
export GREY=0xff939ab7
export GREY_TRANSP=0x11000000
export TRANSPARENT=0x00000000

# Color Palette - Shared between borders and sketchybar
export ACCENT=$YELLOW
export ACCENT_TRANSPARENT=0x44ffe4bf # Transparent version of accent

export BAR_COLOR=0x55000000
export ITEM_BG_COLOR=0x44ffffff # Item background

# Workspace colors by appearance (edit these to tune focused workspace contrast)
export SPACE_ACTIVE_COLOR_DARK=$ACCENT
export SPACE_ACTIVE_BG_COLOR_DARK=$ACCENT_TRANSPARENT
export SPACE_INACTIVE_COLOR_DARK=$WHITE

export SPACE_ACTIVE_COLOR_LIGHT=$WHITE
export SPACE_ACTIVE_BG_COLOR_LIGHT=0xbb000000
export SPACE_INACTIVE_COLOR_LIGHT=$BLACK

# Semantic colors
if [ "$(defaults read -g AppleInterfaceStyle 2>/dev/null)" = "Dark" ]; then
  export TEXT_PRIMARY=$WHITE
  export TEXT_MUTED=$WHITE
  export SPACE_ACTIVE_COLOR=$SPACE_ACTIVE_COLOR_DARK
  export SPACE_ACTIVE_BG_COLOR=$SPACE_ACTIVE_BG_COLOR_DARK
  export SPACE_INACTIVE_COLOR=$SPACE_INACTIVE_COLOR_DARK
else
  export TEXT_PRIMARY=$BLACK
  export TEXT_MUTED=$BLACK
  export SPACE_ACTIVE_COLOR=$SPACE_ACTIVE_COLOR_LIGHT
  export SPACE_ACTIVE_BG_COLOR=$SPACE_ACTIVE_BG_COLOR_LIGHT
  export SPACE_INACTIVE_COLOR=$SPACE_INACTIVE_COLOR_LIGHT
fi

export DEFAULT_ICON_COLOR=$TEXT_PRIMARY
export DEFAULT_LABEL_COLOR=$TEXT_PRIMARY

export SPACE_HIGHLIGHT_COLOR=$ACCENT

export FRONT_APP_LAYOUT_ICON_COLOR=$GREEN
export FRONT_APP_LAYOUT_BG_COLOR=$GREY_TRANSP

export CLOCK_COLOR=$TEXT_MUTED

export VOLUME_COLOR=$GREY

export BATTERY_COLOR_NORMAL=$GREY
export BATTERY_COLOR_WARNING=$YELLOW
export BATTERY_COLOR_LOW=$ORANGE
export BATTERY_COLOR_CRITICAL=$RED
export BATTERY_COLOR_CHARGING=$GREY

export CAL_EVENT_ICON_COLOR=$RED
export CAL_EVENT_LABEL_COLOR=$TEXT_PRIMARY
export CAL_EVENT_BG_COLOR=$GREY_TRANSP

export THINGS_TODO_ICON_COLOR=$YELLOW
export THINGS_TODO_LABEL_COLOR=$TEXT_PRIMARY

export BORDER_ACTIVE_COLOR=0xff3729ac
export BORDER_BACKGROUND_COLOR=0x000000
