#!/usr/bin/env bash

# Black transparency scale (5% -> 95% alpha)
export BLACK_ALPHA_025=0x06000000
export BLACK_ALPHA_05=0x0d000000
export BLACK_ALPHA_075=0x13000000
export BLACK_ALPHA_10=0x1a000000
export BLACK_ALPHA_15=0x26000000
export BLACK_ALPHA_20=0x33000000
export BLACK_ALPHA_25=0x40000000
export BLACK_ALPHA_30=0x4d000000
export BLACK_ALPHA_35=0x59000000
export BLACK_ALPHA_40=0x66000000
export BLACK_ALPHA_45=0x73000000
export BLACK_ALPHA_50=0x80000000
export BLACK_ALPHA_55=0x8c000000
export BLACK_ALPHA_60=0x99000000
export BLACK_ALPHA_65=0xa6000000
export BLACK_ALPHA_70=0xb3000000
export BLACK_ALPHA_75=0xbf000000
export BLACK_ALPHA_80=0xcc000000
export BLACK_ALPHA_85=0xd9000000
export BLACK_ALPHA_90=0xe6000000
export BLACK_ALPHA_95=0xf2000000

export WHITE=0xffffffff
export BLACK=0xff000000

# Rosé Pine palette ingredients (Moon + Dawn)
export ROSE_PINE_MOON_BASE=0xff232136
export ROSE_PINE_MOON_SURFACE=0xff2a273f
export ROSE_PINE_MOON_OVERLAY=0xff393552
export ROSE_PINE_MOON_MUTED=0xff6e6a86
export ROSE_PINE_MOON_SUBTLE=0xff908caa
export ROSE_PINE_MOON_TEXT=0xffe0def4
export ROSE_PINE_MOON_LOVE=0xffeb6f92
export ROSE_PINE_MOON_GOLD=0xfff6c177
export ROSE_PINE_MOON_ROSE=0xffea9a97
export ROSE_PINE_MOON_PINE=0xff3e8fb0
export ROSE_PINE_MOON_FOAM=0xff9ccfd8
export ROSE_PINE_MOON_IRIS=0xffc4a7e7
export ROSE_PINE_MOON_HIGHLIGHT_LOW=0xff2a283e
export ROSE_PINE_MOON_HIGHLIGHT_MED=0xff44415a
export ROSE_PINE_MOON_HIGHLIGHT_HIGH=0xff56526e

export ROSE_PINE_DAWN_BASE=0xfffaf4ed
export ROSE_PINE_DAWN_SURFACE=0xfffffaf3
export ROSE_PINE_DAWN_OVERLAY=0xfff2e9e1
export ROSE_PINE_DAWN_MUTED=0xff9893a5
export ROSE_PINE_DAWN_SUBTLE=0xff797593
export ROSE_PINE_DAWN_TEXT=0xff575279
export ROSE_PINE_DAWN_LOVE=0xffb4637a
export ROSE_PINE_DAWN_GOLD=0xffea9d34
export ROSE_PINE_DAWN_ROSE=0xffd7827e
export ROSE_PINE_DAWN_PINE=0xff286983
export ROSE_PINE_DAWN_FOAM=0xff56949f
export ROSE_PINE_DAWN_IRIS=0xff907aa9
export ROSE_PINE_DAWN_HIGHLIGHT_LOW=0xfff4ede8
export ROSE_PINE_DAWN_HIGHLIGHT_MED=0xffdfdad9
export ROSE_PINE_DAWN_HIGHLIGHT_HIGH=0xffcecacd

if [ "$(defaults read -g AppleInterfaceStyle 2>/dev/null)" = "Dark" ]; then
	# Dark mode
	export FULL_COLOR=$WHITE
	export FULL_COLOR_INVERSE=$BLACK
  export BASE_COLOR=$ROSE_PINE_MOON_BASE
  export SURFACE_COLOR=$ROSE_PINE_MOON_SURFACE
  export OVERLAY_COLOR=$ROSE_PINE_MOON_OVERLAY
  export HIGHLIGHT_LOW=$ROSE_PINE_MOON_HIGHLIGHT_LOW
  export HIGHLIGHT_MED=$ROSE_PINE_MOON_HIGHLIGHT_MED
  export HIGHLIGHT_HIGH=$ROSE_PINE_MOON_HIGHLIGHT_HIGH
  export RED=$ROSE_PINE_MOON_LOVE
  export GREEN=$ROSE_PINE_MOON_PINE
  export BLUE=$ROSE_PINE_MOON_FOAM
  export YELLOW=$ROSE_PINE_MOON_GOLD
  export ORANGE=$ROSE_PINE_MOON_ROSE
  export MAGENTA=$ROSE_PINE_MOON_IRIS
  export MUTED_COLOR=$ROSE_PINE_MOON_MUTED
  export SUBTLE_COLOR=$ROSE_PINE_MOON_SUBTLE
  export TEXT_COLOR=$ROSE_PINE_MOON_TEXT
else
	# Light mode
	export FULL_COLOR=$BLACK
	export FULL_COLOR_INVERSE=$WHITE
  export BASE_COLOR=$ROSE_PINE_DAWN_BASE
  export SURFACE_COLOR=$ROSE_PINE_DAWN_SURFACE
  export OVERLAY_COLOR=$ROSE_PINE_DAWN_OVERLAY
  export HIGHLIGHT_LOW=$ROSE_PINE_DAWN_HIGHLIGHT_LOW
  export HIGHLIGHT_MED=$ROSE_PINE_DAWN_HIGHLIGHT_MED
  export HIGHLIGHT_HIGH=$ROSE_PINE_DAWN_HIGHLIGHT_HIGH
  export RED=$ROSE_PINE_DAWN_LOVE
  export GREEN=$ROSE_PINE_DAWN_PINE
  export BLUE=$ROSE_PINE_DAWN_FOAM
  export YELLOW=$ROSE_PINE_DAWN_GOLD
  export ORANGE=$ROSE_PINE_DAWN_ROSE
  export MAGENTA=$ROSE_PINE_DAWN_IRIS
  export MUTED_COLOR=$ROSE_PINE_DAWN_MUTED
  export SUBTLE_COLOR=$ROSE_PINE_DAWN_SUBTLE
  export TEXT_COLOR=$ROSE_PINE_DAWN_TEXT
fi

# Bar background by appearance.
export BAR_COLOR=$BASE_COLOR

export ITEM_BG_COLOR=$HIGHLIGHT_HIGH

export TEXT_PRIMARY=$TEXT_COLOR
export TEXT_MUTED=$MUTED_COLOR

export SPACE_ACTIVE_COLOR=$FULL_COLOR_INVERSE
export SPACE_ACTIVE_BG_COLOR=$YELLOW
export SPACE_INACTIVE_COLOR=$TEXT_COLOR

export THINGS_TODO_ICON_COLOR=$BLUE
export THINGS_TODO_LABEL_COLOR=$TEXT_PRIMARY

export DEFAULT_ICON_COLOR=$TEXT_PRIMARY
export DEFAULT_LABEL_COLOR=$TEXT_PRIMARY

export FRONT_APP_LAYOUT_ICON_COLOR=$RED
export FRONT_APP_LAYOUT_BG_COLOR=$GREY_TRANSP

export CLOCK_COLOR=$TEXT_COLOR

export VOLUME_COLOR=$GREY

export BATTERY_COLOR_NORMAL=$MAGENTA
export BATTERY_COLOR_WARNING=$YELLOW
export BATTERY_COLOR_LOW=$ORANGE
export BATTERY_COLOR_CRITICAL=$RED
export BATTERY_COLOR_CHARGING=$GREEN

export CAL_EVENT_ICON_COLOR=$RED
export CAL_EVENT_LABEL_COLOR=$TEXT_COLOR

export BORDER_ACTIVE_COLOR=$MAGENTA
export BORDER_BACKGROUND_COLOR=$BLACK_ALPHA_05
