#!/bin/bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

# Shared typography
STATUS_LABEL_FONT="SF Pro:Semibold:13.0"
STATUS_SYMBOL_ICON_FONT="SF Pro:Bold:14.0"
THINGS_ICON_FONT="sketchybar-app-font:Regular:14.0"

# Load colors
source "$CONFIG_DIR/colors.sh"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar \
  position=top \
  height=36 \
  blur_radius=0 \
  color=$BAR_COLOR \
  margin=16 \
  corner_radius=12 \
  y_offset=12 \
  padding_left=3 \
  padding_right=2 \
  border_color=0x19000000 \
  border_width=1

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=0
  padding_right=0
  icon.font="Hack Nerd Font:Regular:14.0"
  label.font="SF Pro:Semibold:13.0"
  icon.color=$DEFAULT_ICON_COLOR
  label.color=$DEFAULT_LABEL_COLOR
  icon.padding_left=10
  icon.padding_right=10
  label.padding_left=0
  label.padding_right=10
  background.padding_left=4
  background.padding_right=4
)
sketchybar --default "${default[@]}"

# Set up non-rendering items and events
sketchybar --add event aerospace_workspace_change \
           --add event aerospace_mode_changed \
           --add event appearance_change AppleInterfaceThemeChangedNotification \
           --add item appearance_listener center \
           --set appearance_listener drawing=off script="$PLUGIN_DIR/appearance.sh" \
           --subscribe appearance_listener appearance_change

# Aerospace workspaces
for sid in $(aerospace list-workspaces --all); do
  # Determine icon based on workspace ID
  space_icon=""
  case "$sid" in
  a1) space_icon="↖" ;;
  b1) space_icon="Q" ;;
  b2) space_icon="W" ;;
  b3) space_icon="E" ;;
  b4) space_icon="R" ;;
  *) space_icon="$sid" ;;
  esac

  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change \
    --set space.$sid \
    drawing=off \
    background.color=$TRANSPARENT \
    background.corner_radius=6 \
    background.height=24 \
    background.drawing=off \
    background.padding_left=4 \
    background.padding_right=4 \
    icon="$space_icon" \
    icon.font="SF Pro:Bold:16.0" \
    icon.highlight_color=$SPACE_HIGHLIGHT_COLOR \
    label.drawing=off \
    label.font="sketchybar-app-font:Regular:14.0" \
    click_script="aerospace workspace $sid" \
    script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done


##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
  --set clock \
  update_freq=10 \
  script="$PLUGIN_DIR/clock.sh" \
  icon.font="$STATUS_SYMBOL_ICON_FONT" \
  label.font="$STATUS_LABEL_FONT" \
  --add item battery right \
  --set battery update_freq=120 icon.drawing=on script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change \
  --add item calendar_event right \
  --set calendar_event \
  update_freq=60 \
  script="$PLUGIN_DIR/calendar_event.sh" \
  click_script="open -a Calendar" \
  icon.font="$STATUS_SYMBOL_ICON_FONT" \
  label.font="$STATUS_LABEL_FONT" \
  label.color="$CAL_EVENT_LABEL_COLOR" \
  --add item things_todo right \
  --set things_todo \
  update_freq=20 \
  script="$PLUGIN_DIR/things_todo.sh" \
  click_script="open -a Things3" \
  icon.font="$THINGS_ICON_FONT" \
  label.font="$STATUS_LABEL_FONT" \
  background.corner_radius=8 \
  background.height=26

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
