set guifont=Menlo:h13             " Font family and font size.
set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions=aAce               " Hide toolbar, disable scrollbars.
set lines=36 columns=99           " Window dimensions.

