#!/bin/sh

editor=vim
[[ -f ~/bin/mvim ]] && editor=mvim

if [[ -f README ]]; then
	read -s -n 1 -p 'Rename and edit this README? [y/n]'
	case $REPLY in
		'Y' | 'y' )
		mv README README.md && $editor README.md ;;
		'N' | 'n' )
		exit 0 ;;
		* )
		echo "\n\"$REPLY\" is not a valid input." ;;
	esac
	exit 0
else
	$editor README.md
fi
